services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nfedb
      POSTGRES_USER: nfeuser
      POSTGRES_PASSWORD: nfepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nfeuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://nfeuser:nfepass@db:5432/nfedb
      - SECRET_KEY=sua_chave_secreta_aqui_123456
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - UPLOAD_DIR=uploads
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
