services:
  # Backend FastAPI (usando SQLite)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: nfe_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./nfe_system.db
      - SECRET_KEY=sua_chave_secreta_docker_123456
      - DEBUG=True
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - UPLOAD_DIR=uploads
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/nfe_system.db:/app/nfe_system.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    networks:
      - nfe_network

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: nfe_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - nfe_network


networks:
  nfe_network:
    driver: bridge